language: python
python:
- '2.7'
jobs:
  include:
  - stage: code-quality
    name: Ensure code is PEP8 compliant
    install:
    - pip install -r requirements.txt
    - pip install flake8
    script:
    - python -m flake8 --statistics --count --ignore E722,E501 bin/*.py
    - python -m flake8 --statistics --count --ignore E722,E501 cvprac_abstraction/*.py
  - stage: code-load
    name: Test code is correctly loaded
    install:
    - pip install -r requirements.txt
    script:
    - pip install git+https://github.com/titom73/arista-cvp-scripts.git
    - python bin/cvp-configlet-manager.py -h
    - python bin/cvp-container-manager.py -h
    - python bin/cvp-configlet-backup.py -h
    - python bin/cvp-task-manager.py -h
  - stage: installation
    name: Test installation process from original respository
    script:
    - pip install git+https://github.com/titom73/arista-cvp-scripts.git
    - cvp-configlet-manager -h
    - cvp-container-manager -h
    - cvp-configlet-backup -h
    - cvp-task-manager -h
  - stage: pypi-deploy
    name: Push package to pypi servers
    script:
    - echo "deploy to test.pypi.org"
    deploy:
      provider: pypi
      username: titom73
      skip_existing: true
      password:
        secure: SiCZUeZOAyTjB9+lq8chh5lSA+/M2uma0vxj2j+uiuFVNbHIdwhPnWi1Hu71tGDUSO9j827HE7DhNHhjDqDpfA8rHOyHm/2KM9tiGjyTS65AB6mI2jQP/34m/6tYxM+zof56jU5Tn9zlNR2XqBqlhRwMMFrjcT+9B1CFCPE7/8/K7Sw48Vw0DltQzpQPQ34g2TbcTFydWJu4kJCONVHnY1x2jmddda6iJc6Lkg6enSHEDPccHdOXcaMjGc4+ST4uCPEi+1CzCVhItmviqBclVxZvYC8cKzslMaE2sohgsuPkhyVcZYqwCXyoDBFHZMo08A3DdSkksxbnewS2LSZ5HzWkBEiqGQwbJLnl6uy9gMqLlfVDHHIOloAi0OcakX1LmOJDlD+M4M39GvVDHZJL9MIxkt4RxTM+yuYb8GWxYAs8yqBk3Jr7zs55/eEAIHvKyTBm6NoDg01K6TT0mO6ecsA1yMWEDYqwHPBXQsj4S0oM1JgvvJ6u17LcTcLcjFBTu63eHgEy3tlTB0ds53vruNBTN4OVs5/IGmcI2YuJvMIXbON+KewvVMKTAn7fr5eQN5JZW77WbP3UgZheT+oFp1vrTDAuwyp0ShAmZrpj6RsLC0dWSdsHIy98gFlfx+Vj1Ox0fJcD8FscvGhJKwQ0TdKa1cBPSB6/NapHGG36Cxg=
      on:
        tags: true
        distributions: sdist bdist_wheel
        repo: titom73/arista-cvp-scripts
