---
language: python
python:
  - "2.7"
# command to install dependencies
jobs:
  include:
    - stage: code-quality
      install:
        - pip install -r requirements.txt
        - pip install flake8
      # command to run tests
      script:
        - python -m flake8 --statistics --count --ignore E722,E501 bin/*.py
        - python -m flake8 --statistics --count --ignore E722,E501 cvprac_abstraction/*.py
    - stage: code-load
      install:
        - pip install -r requirements.txt
      # command to run tests
      script: 
        - pip install git+https://github.com/titom73/arista-cvp-scripts.git
        - python bin/cvp-configlet-manager.py -h
        - python bin/cvp-container-manager.py -h
        - python bin/cvp-configlet-backup.py -h
        - python bin/cvp-task-manager.py -h

    - stage: installation
      # command to run tests
      script: 
        - pip install git+https://github.com/titom73/arista-cvp-scripts.git
        - cvp-configlet-manager -h
        - cvp-container-manager -h
        - cvp-configlet-backup -h
        - cvp-task-manager -h
